name: pyleiades 
dependencies:
  - coverage=4.5.3
  - matplotlib=3.0
  - numpy=1.16
  - pandas=0.24.2
  - pip=19.0
  - pytest=4.3
  - pytest-cov=2.6.1
  - python=3.7
  - seaborn=0.9
  - setuptools=40.8.0
  - xlrd=1.2.0
